name: Publish Docker Image
 
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Push Image

    runs-on: ubuntu-latest

    env:
      IMAGE: docker.pkg.github.com/${{ github.repository }}/docker-push-without-repo-scope

    steps:
      - run: docker pull alpine

      - run: docker tag alpine ${{ env.IMAGE }}

      - run: docker login https://docker.pkg.github.com -u token -p ${{ secrets.WRITE_PACKAGES_TOKEN }}

      - run: docker push ${{ env.IMAGE }}
